name: 'kpenfound'
description: 'Multiplatform action'
author: 'kpenfound'
inputs:
  script:
    required: true
    description: 'path to a python file'
outputs:
  stdout:
    description: 'stdout from the executed python file'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/src/scripts/action.sh
      shell: bash
      env:
        INPUT_SCRIPT: ${{ inputs.script }}
