name: 'release'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    tags:
      - '*'

jobs:
  release: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Dagger release
        env:
          RELEASE: true
          GH_ELEVATED_TOKEN: ${{ secrets.GH_ELEVATED_TOKEN }}
        run: go run ci/main.go
